### ISSUE TITLE
Mouse buttons don't work for keybind

### ISSUE THREAD

**Issue by qwerasd205** [wisp-forest/ok-boomer#3]
Pretty straight forward- can't use mouse buttons as the keybinds. When I set them, they don't do anything when pressed.

- macOS
- 1.19.3
- Quilt Loader 0.17.11
- Ok Boomer v0.1.0
- owo-lib v0.10.2

To reproduce:
- Set keybind for boom to any mouse button (ex. `Mouse 1`, `Mouse 5`)
- Attempt to boom

(Not tested without other mods- may be mod conflict-- if you can't reproduce it, I'll check)

**Comment by gliscowo** [comment]
Thanks for reporting, this is now fixed in [0.1.1](https://modrinth.com/mod/ok-boomer/version/Nkz8Qsnn)
Cheers
